#!/usr/bin/env bash
set -ex

OUT=target/

MODEL=cpp17

if [ ! -z "$1" ]; then
   MODEL=$1
fi

CONF=model/${MODEL}.cfg

if [ ${MODEL} = "multi" ]; then
    CONF=model/cpp17.cfg
    CONF11=model/cpp11.cfg
    for f in `find tests -name "*.litmus" -type f`; do
	if [[ ${f} == *"cpp11"* ]]; then
	    herd7  -o ${OUT} -conf ${CONF11} -timeout none ${f} &> ${f}.expected &
	else
	    herd7  -o ${OUT} -conf ${CONF} -timeout none ${f} &> ${f}.expected &
	fi
    done
else
    for f in `find tests -name "*.litmus" -type f`; do
	herd7  -o ${OUT} -conf ${CONF} -timeout none ${f} &> ${f}.expected &
    done
fi

wait

for f in `find tests -name "*.litmus" -type f`; do
    sed -i  '' '/^Time/d' ${f}.expected &
done

wait

set +x
echo "CHECK: Undefined Behavior..."
for f in `find tests -name "*.litmus" -type f`; do
    # TODO: fix these eventually
    if [[ ${f} == *"popl15"* ]] || [[ ${f} == *"dat3m"* ]] || [[ ${f} == *"mp"* ]]; then
	continue
    fi
    echo ${f}
    if [[ ${f} == *"undef"* ]]; then
	if ! grep -q Undef ${f}.expected; then
	    echo "  ERROR: no undefined behavior"
	fi
    else
	if grep -q Undef ${f}.expected; then
	    echo "  ERROR: undefined behavior"
	fi
    fi
done
