#!/usr/bin/env bash
set -ex

OUT=target/

MODEL=multi

if [ ! -z "$1" ]; then
   MODEL=$1
fi

CONF=model/${MODEL}.cfg
COUNT=0
if [ ${MODEL} = "multi" ]; then
    CONF=model/cpp17.cfg
    CONF11=model/cpp11.cfg
    for f in `find tests -name "*.litmus" -type f`; do
	if [[ ${f} == *"cpp11"* ]]; then
	    herd7  -o ${OUT} -conf ${CONF11} -timeout none ${f} &> ${f}.expected &
	else
	    herd7  -o ${OUT} -conf ${CONF} -timeout none ${f} &> ${f}.expected &
	fi
	# Too many concurrent processes limit:
	COUNT=$(($COUNT + 1))
	if ! (($COUNT % 1000)); then
	    sleep 2
	fi
    done
else
    for f in `find tests -name "*.litmus" -type f`; do
	herd7  -o ${OUT} -conf ${CONF} -timeout none ${f} &> ${f}.expected &
	# Too many concurrent processes limit:
	COUNT=$(($COUNT + 1))
	if ! (($COUNT % 1000)); then
	    sleep 2
	fi
    done
fi

wait

for f in `find tests -name "*.litmus" -type f`; do
    sed -i  '' '/^Time/d' ${f}.expected &
done

wait

set +x
echo "CHECK: Undefined Behavior..."
FAILURES_NOT_OK=0
FAILURES_NOT_UB=0
FAILURES_UB=0
for f in `find tests -name "*.litmus" -type f`; do
    # TODO: fix these eventually
    if [[ ${f} == *"popl15"* ]] || [[ ${f} == *"pldi17"* ]] || [[ ${f} == *"dat3m"* ]] || [[ ${f} == *"paul"* ]] || [[ ${f} == *"progress"* ]]; then
	continue
    fi
    echo ${f}
    if [[ ${f} == *"undef"* ]]; then
	if ! grep -q Undef ${f}.expected; then
	    echo "  ERROR: no undefined behavior"
	    FAILURES_NOT_UB=$((${FAILURES_NOT_UB}+1))
	fi
    else
	if grep -q Undef ${f}.expected; then
	    echo "  ERROR: undefined behavior"
	    FAILURES_UB=$((${FAILURES_UB}+1))
	fi
	if ! grep -q Ok ${f}.expected; then
	    echo "  ERROR: not Ok!"
	    FAILURES_NOT_OK=$((${FAILURES_NOT_OK}+1))
	fi	
    fi
done
if [[ $FAILURES_NOT_UB != "0" ]] || [[ $FAILURES_NOT_OK != "0" ]] || [[ $FAILURES_UB != "0" ]]; then
    echo "ERROR: tests failed:"
    echo "  Should be Undefined:       ${FAILURES_NOT_UB}"
    echo "  Should be Well-Defined:    ${FAILURES_UB}"
    echo "  Should be OK+Well-Defined: ${FAILURES_NOT_OK}"
    
    exit 1
else
    echo "Undefined Behavior check: SUCCESS."
fi
